---
title: "Gráficos de los casos de COVID-19 en el Perú"
date: "Actualizado al 2020-03-16"
output: html_document
---


```{r echo=FALSE, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE
)

library(tidyverse)
library(rnaturalearth)
library(mapview)
library(patchwork)
library(echarts4r)
library(echarts4r.maps)

pe_sf <- ne_states(country = "peru", returnclass = "sf") %>%
  select(
    iso_3166_2,
    geometry
  )

covid_pe <- read_csv(
  "covid-19-peru-data-con-ubigeos.csv"
) %>%
  filter(!is.na(iso_3166_2_code)) %>%
  select(region, iso_3166_2_code, date, confirmed)


pe_map_data <- merge(
  pe_sf,
  covid_pe,
  by.x = "iso_3166_2",
  by.y = "iso_3166_2_code"
)


pe_map <-   mapview(
  pe_map_data,
  zcol = "region",
  layer.name = "Base",
  legend = FALSE
)

fechas <- as.character(sort(unique(pe_map_data$date)))

for (d in sort(unique(pe_map_data$date))) {
  layer_name <- as.character(unique(pe_map_data[pe_map_data$date == d, ]$date))[1]
  pe_map <- pe_map +
    mapview(
      pe_map_data %>% filter(date == d),
      zcol = "confirmed",
      layer.name = layer_name,
      legend = TRUE
    )
}
```

## Mapa interactivo de casos confirmados por región

```{r echo=FALSE}
covid_reg_pe <- read_csv(
  "covid-19-peru-data.csv"
) %>% 
  filter(!is.na(region)) %>%
  select(region, date, confirmed)

covid_reg_pe %>% 
  group_by(date) %>% 
  e_charts(region, timeline=TRUE) %>%
  em_map("Peru") %>% 
  e_map(confirmed, map = "Peru") %>% 
  e_visual_map(min = 1, max = 100) %>% 
  e_tooltip(formatter = e_tooltip_choro_formatter("decimal")) %>% 
  e_title(
    text = "Mapa interactivo de casos por región", 
    subtext = "Fuente original: Tweets del MINSA https://twitter.com/Minsa_Peru"
  ) %>% 
  e_theme("infographic")
```



## Mapa de casos por región (diferentes capas)

```{r echo=FALSE}
pe_map
```

## Gráfico de casos por región

```{r echo=FALSE}
ggplot(covid_pe,
  aes(x = date, y = confirmed, color = region)) +
  geom_point(show.legend = FALSE) +
  geom_segment(aes(xend = date, yend = 0), size = 1, show.legend = FALSE) +
  facet_wrap(~region, scales = "free_y", ncol = 3) +
  theme_minimal() +
  labs(
    y = "Casos Confirmados",
    x = "",
    title = "COVID-19: Casos Confirmados por region en el Perú",
    subtitle = "Fuente: Tweets del MINSA https://twitter.com/Minsa_Peru",
    caption = paste0("Actualizado el ", lubridate::now(tzone = "UTC"), " UTC // @jmcastagnetto, Jesús M. Castagnetto")
  )
```

## Gráficos de casos confirmados y descartados en todo el Perú

```{r echo=FALSE,fig.width=12}
covid_pe <- read_csv(
  "covid-19-peru-data-con-ubigeos.csv"
) %>%
  filter(is.na(iso_3166_2_code)) %>%
  select(date, confirmed, discarded_cases)

p1 <- ggplot(covid_pe,
       aes(x = date, y = confirmed)) +
  geom_point(show.legend = FALSE) +
  geom_segment(aes(xend = date, yend = 0), size = 1, show.legend = FALSE) +
  theme_minimal() +
  labs(
    y = "Número de casos",
    x = "",
    title = "COVID-19: Casos confirmados en el Perú",
    subtitle = "Fuente: Tweets del MINSA https://twitter.com/Minsa_Peru",
    caption = paste0("Actualizado el ", lubridate::now(tzone = "UTC"), " UTC // @jmcastagnetto, Jesús M. Castagnetto")
  )

p2 <- ggplot(covid_pe,
             aes(x = date, y = discarded_cases)) +
  geom_point(show.legend = FALSE) +
  geom_segment(aes(xend = date, yend = 0), size = 1, show.legend = FALSE) +
  theme_minimal() +
  labs(
    y = "Número de casos descartados",
    x = "",
    title = "COVID-19: Casos descartados en el Perú",
    subtitle = "Fuente: Tweets del MINSA https://twitter.com/Minsa_Peru",
    caption = paste0("Actualizado el ", lubridate::now(tzone = "UTC"), " UTC // @jmcastagnetto, Jesús M. Castagnetto")
  )

p1 + p2
```




- Datos en: https://github.com/jmcastagnetto/covid-19-peru-data
- Fuente original: Tweets del [@Minsa_peru](https://twitter.com/Minsa_Peru)